<a href="https://colab.research.google.com/github/WD-Projects/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Numpy***
NumPy (short for Numerical Python) is a Python library used for working with numbers, arrays, matrices, and mathematical calculations.
The most important thing to learn first in NumPy is the array.

In [ ]:
#np.array
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a))
print(a*2)

[1 2 3]
<class 'numpy.ndarray'>
[2 4 6]


In [ ]:
#2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#dtype
d = np.array([1,2,3], dtype=float)
print(d)

[1. 2. 3.]


In [ ]:
#np.arange(minnumber,maxnumber,skip)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#reshape
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
np.arange(1,33).reshape(4,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]],


       [[[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]],


       [[[25, 26],
         [27, 28]],

        [[29, 30],
         [31, 32]]]])

In [ ]:
#np.ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#np.zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#np.linspace(minnumber,maxnumber,number of elements in range)
np.linspace(-10,10,10)

In [ ]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#random
from numpy import random
random.random(5)

array([0.30954121, 0.61379387, 0.79824526, 0.593298  , 0.31208145])

In [ ]:
np.random.random((3,4)) #((row,column))

array([[0.18636204, 0.64732008, 0.68272508, 0.3550278 ],
       [0.26593017, 0.22476055, 0.26999081, 0.43115266],
       [0.54481111, 0.87925038, 0.58387923, 0.11532764]])

In [ ]:
arr1 = np.arange(1,13, dtype=np.int32).reshape(6,2)
arr2 = np.arange(1,13, dtype=float).reshape(3,2,2)
arr3 = np.arange(1,33).reshape(4,2,2,2)

# ***Array attributes***

In [ ]:
#ndim
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

2
3
4


In [ ]:
#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(6, 2)
(3, 2, 2)
(4, 2, 2, 2)


In [ ]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int32
float64
int64


In [ ]:
#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

12
12
32


In [ ]:
#itemsize
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

4
8
8


# ***Changing Data types***

In [ ]:
#astype
arr1.astype(np.int16)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int16)

# ***Array Operations***

In [ ]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(12,24).reshape(3,4)

In [ ]:
#arithmatic scalar operations
arr1 * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [ ]:
arr2 + 10

array([[22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33]])

In [ ]:
arr1 ** 2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [ ]:
arr1 % 2

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [ ]:
arr1 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])

In [ ]:
#relational scalar operation(<, >, <=, >=, ==)
arr1 >= 5

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#vector operations
arr1 + arr2

array([[13, 15, 17, 19],
       [21, 23, 25, 27],
       [29, 31, 33, 35]])

In [ ]:
arr1 * arr2

array([[ 12,  26,  42,  60],
       [ 80, 102, 126, 152],
       [180, 210, 242, 276]])

# ***Array Functions***

In [ ]:
arr1 = np.random.random((3,4))
arr1 = np.round(arr1*100)
arr1
# arr1 = np.round(arr1, 2) -> round(number, no. of digits after decimals)

array([[47., 95.,  3.,  9.],
       [23.,  7., 87., 40.],
       [99., 51., 71., 95.]])

In [ ]:
#max/min/sum/prod
#axis=0->col, axis=1->row
np.max(arr1)

np.float64(99.0)

In [ ]:
np.min(arr1)

np.float64(3.0)

In [ ]:
np.sum(arr1)

np.float64(627.0)

In [ ]:
np.prod(arr1)#it will multiply the all elements of an array

np.float64(2.300263944147477e+18)

In [ ]:
np.max(arr1, axis=0)

array([99., 95., 87., 95.])

In [ ]:
np.sum(arr1, axis=1)

array([154., 157., 316.])

In [ ]:
#mean/median/std/var
np.mean(arr1, axis=1)

array([38.5 , 39.25, 79.  ])

In [ ]:
np.median(arr1, axis=0)

array([47., 51., 71., 40.])

In [ ]:
np.std(arr1)

np.float64(35.09303112205233)

In [ ]:
np.var(arr1)

np.float64(1231.5208333333333)

In [ ]:
#dot product
arr2 = np.arange(1,13).reshape(3,4)
arr3 = np.arange(12,24).reshape(4,3)
np.dot(arr2,arr3)

array([[180, 190, 200],
       [444, 470, 496],
       [708, 750, 792]])

In [ ]:
#log/exp(exponents)
np.log(arr1)

array([[3.8501476 , 4.55387689, 1.09861229, 2.19722458],
       [3.13549422, 1.94591015, 4.46590812, 3.68887945],
       [4.59511985, 3.93182563, 4.26267988, 4.55387689]])

In [ ]:
np.exp(arr1)

array([[2.58131289e+20, 1.81123908e+41, 2.00855369e+01, 8.10308393e+03],
       [9.74480345e+09, 1.09663316e+03, 6.07603023e+37, 2.35385267e+17],
       [9.88903032e+42, 1.40934908e+22, 6.83767123e+30, 1.81123908e+41]])

In [ ]:
#round/floor/ceil
np.round(np.random.random((3,4))*100)

array([[54.,  2., 21., 73.],
       [22., 50.,  8., 77.],
       [69., 42.,  2., 81.]])

In [ ]:
np.floor(np.random.random((3,4))*100)

array([[44., 48., 98., 97.],
       [78., 92., 57., 48.],
       [ 3., 79., 62., 27.]])

In [ ]:
np.ceil(np.random.random((3,4))*100)

array([[49.,  1., 78., 77.],
       [55., 41., 62., 90.],
       [35., 89., 37., 29.]])

# ***Indexing***

In [ ]:
arr1 = np.arange(10)
arr2 = np.arange(12).reshape(3,4)
arr3 = np.arange(27).reshape(3,3,3)

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1[-1]

np.int64(9)

In [ ]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr2[1,2]

np.int64(6)

In [ ]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr3[1,1,1]

np.int64(13)

# ***Slicing***

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1[2:5]

array([2, 3, 4])

In [ ]:
arr1[2:6:2]

array([2, 4])

In [ ]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
arr2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
arr2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr3[1,:,1:]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [ ]:
arr3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
arr3[::2,1,1:]

array([[ 4,  5],
       [22, 23]])

# ***Iterating***

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in arr1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in arr2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in arr3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in np.nditer(arr2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for i in np.nditer(arr3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# ***Reshaping***

In [ ]:
#reshape
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#Transpose
np.transpose(arr2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#ravel
arr3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# ***Stacking***

In [ ]:
arr4 = np.arange(12).reshape(3,4)
arr5 = np.arange(12,24).reshape(3,4)

In [ ]:
#horizontal stacking
np.hstack((arr4,arr5,arr4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [ ]:
#vertical stacking
np.vstack((arr4,arr5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# ***Spliting***

In [ ]:
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#horizontal spliting
np.hsplit(arr4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
arr5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#vertical spliting
np.vsplit(arr5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]